### ISSUE TITLE
collate not support  Unicode Variation Selector

### ISSUE THREAD

**Issue by n2029-ndensan** [dverite/icu_ext#14]
I hope  supported Unicode Variation Selector on collate.

D209007=# create table ivstesticu (
D209007(# moji text
D209007(# );
D209007=# CREATE UNIQUE INDEX idx ON ivstesticu((icu_sort_key(moji, 'ja_JP'))); 
D209007=# insert into ivstesticu (moji) values ( U&'\+003436' || U&'\+E0101' || U&'\+00304D');  
D209007=# insert into ivstesticu (moji) values ( U&'\+003436' || U&'\+00304D'); 
D209007=# select moji from ivstesticu where moji like '%' || U&'\+003436' || '%' ;  
------
㐶󠄁き
㐶き
(2 行)

expected
------
 㐶き
(1 行)

**Comment by dverite** [comment]
Your Unicode sequences seem wrong at the syntax level.
I assume you mean the two strings to be `U&'\+003436\+00304D'` and `U&'\+003436\+0E0101\+00304D'`
These two strings have an identical sort key at the default strength collation level, so the UNIQUE index you're setting would prevent to have them as two distinct rows.

The point is not that the LIKE operator should find one row instead of two, it's that there couldn't be two rows in the first place.


daniel=> **create table ivstesticu (moji text);**
CREATE TABLE

daniel=> **CREATE UNIQUE INDEX idx ON ivstesticu((icu_sort_key(moji, 'ja_JP')));**
CREATE INDEX

daniel=> **insert into ivstesticu values(U&'\+003436\+0E0101\+00304D');**
INSERT 0 1

daniel=> **insert into ivstesticu values(U&'\+003436\+00304D');**
ERROR:  duplicate key value violates unique constraint "idx"
DETAIL:  Key (icu_sort_key(moji, 'ja_JP'::text))=(\xdc0ad65e1401060106) already exists.

**Comment by n2029-ndensan** [comment]
very sorry.

D209007=# select  U&'\\+003436\\+0E0101\\+00304D';
 ?column?
----------
 㐶󠄁き
(1 行)

D209007=# insert into ivstesticu (moji) values (U&'\\+003436\\+0E0101\\+00304D');
INSERT 0 1
D209007=# insert into ivstesticu (moji) values (U&'\\+003436\\+00304D');
ERROR:  duplicate key value violates unique constraint "idx"
DETAIL:  Key (icu_sort_key(moji, 'ja_JP'::text))=(\xdc0a0e5d1401060106) already exists.

Is this normalizing internally?
I want a collation that treats variant characters as separate characters without normalizing.

**Comment by dverite** [comment]
"normalizing" in Unicode has a specific meaning, which I believe does not apply here:
https://www.unicode.org/faq/normalization.html

On the differences of these two strings
`icu_sort_key(U&'\+003436\+0E0101\+00304D', 'ja_JP')` and `icu_sort_key(U&'\+003436\+0E0101\+00304D', 'ja_JP')` produce the same result because according to ICU, this U+E0101 codepoint (https://codepoints.net/U+E0101) is not relevant in the string comparison when 'ja_JP' is used as the collation, with the default collation strength.

To tell ICU that you want them to be considered different while still having 'ja-JP' for the language, you may use `'ja-JP-u-ks-identic'` as the collation (note the minus sign instead of the underscore between ja and JP. If you use underscore, the parsing of the rest of the string does not recognize the collation options).

**Comment by n2029-ndensan** [comment]
Thank you for a polite answer.

ja-JP is not particular about it. For normal use, use C.

I just tried what you suggested.
Insert is now possible. Thank you.

However, Select hits two rows.


drop index idx;
CREATE UNIQUE INDEX idx ON ivstesticu((icu_sort_key(moji, 'ja-JP-u-ks-identic')));
delete from ivstesticu where moji like '%' || U&'\\+003436' || '%' ;
insert into ivstesticu (moji) values (U&'\\+003436\\+0E0101\\+00304D');
insert into ivstesticu (moji) values (U&'\\+003436\\+00304D');
select moji from ivstesticu where moji like '%' || U&'\\+003436' || '%' ;
 moji
\---------
 㐶󠄁き
 㐶き
(2 行)

**Comment by dverite** [comment]
This LIKE pattern  ( `'%' || U&'\+003436' || '%'`  ) matches strings containing the codepoint U+3436. Both strings contain this codepoint so both strings match. The LIKE operator as it is now implemented in PostgreSQL doesn't know or care about variation selectors in UTF-8 strings, and more generally it doesn't interpret any codepoint with regard to Unicode rules.
