### ISSUE TITLE
Not working with PostgreSQL 11.4?

### ISSUE THREAD

**Issue by gruenerWald** [dverite/icu_ext#2]
I didn't manage to work icu-extension on PostgreSQL 11.4. make and make install was done without error, almost without error. At make the file unicode/ucol.h was missing, but I managed this by installing libicu-dev.
The extension icu_ext appears when I submit the query "SELECT * FROM pg_available_extensions. But when I try "CREATE EXTENSION icu_ext", there is an error: There is no installation script or update path for version 1.4.
Did you try to install the extension in version 11.4 and did it work? Have I done anything wrong?

**Comment by dverite** [comment]
Yes, this should work with PG 11.4

After make install (of icu_ext) there should be icu_ext--1.3.sql and icu_ext--1.3--1.4.sql in the extension directory (/usr/share/postgresql/11/extension if you're using Debian packages)
and `SELECT * FROM pg_available_extensions WHERE name='icu_ext'` should report 1.4 in the default_version column due to the presence of these files.

Do you see something different?

**Comment by gruenerWald** [comment]
Thank you for your hints. The query `SELECT * FROM pg_available_extensions WHERE name='icu_ext'` reported 1.4 in the default_version column. The problem was that in the directory /usr/share/postgresql/11/extension was only the file icu_ext.control, not your mentioned sql files.

But when I copied those sql files from the cloning directory in the extension directory, I was able to do the `CREATE EXTENSION` query and add the extension to the database. It's working now :-)
